---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Deploy custom HTML page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: yes
